roles/install-docker/tasks/main.yaml
As result of this change:  [#71537](https://github.com/ansible/ansible/pull/71537) ansible started ensuring packages are gpg-verified.
Thus the ansible playbook install-k8s.yml is failing with the error "Failed to validate GPG signature for docker-ce-3:19.03.8-3.el7.ppc64le" 
ansible version 2.9.13
=> Adding disable_gpg_check flag to install-docker role

group_vars/all
This change is for overriding the ssh private key during runtime
=> override the ssh private key

group_vars/all, roles/install-docker/templates/daemon.j2
More information:
https://www.docker.com/blog/scaling-docker-to-serve-millions-more-developers-network-egress/
https://cloud.google.com/container-registry/docs/pulling-cached-images#configure
=> Add mirror docker registry

roles/runtime/tasks/main.yaml
"periodic-kubernetes-conformance-test-ppc64le" job that runs conformance suite against k8s cluster has been failing with below error:
```
TASK [runtime : Enable and start docker] ***************************************
fatal: [130.198.3.122]: FAILED! => {"changed": false, "msg": "Unable to start service docker: Job for docker.service failed because the control process exited with error code.\nSee \"systemctl status docker.service\" and \"journalctl -xe\" for details.\n"}
```
The reason in the logs is:
```
WARN[2021-01-08T10:49:34.195479749Z] Failed to find iptables: exec: "iptables": executable file not found in $PATH
INFO[2021-01-08T10:49:34.197613982Z] stopping event stream following graceful shutdown  error="<nil>" module=libcontainerd namespace=moby
failed to start daemon: Error …
```
=> Adding iptables as common prerequisite for runtime

roles/install-calico/tasks/main.yml
This change is to avoid the below error on PowerVS while the conformance jobs use the ansible playbook to create k8s cluster.
```
TASK [install-calico : Download calico manifest] *******************************
fatal: [163.68.65.236]: FAILED! => {"changed": false, "dest": "/tmp/calico.yaml", "elapsed": 10, "msg": "Request failed: <urlopen error _ssl.c:880: The handshake operation timed out>", "url": "https://docs.projectcalico.org/manifests/calico.yaml"}
```
https://github.ibm.com/powercloud/container-dev/issues/1467 has more details.
As `get_url` module of ansible doesn't have the option to limit the download rate, switching to shell and then `wget`.
https://prow.ppc64le-cloud.org/view/gs/ppc64le-kubernetes/logs/periodic-kubernetes-conformance-test-ppc64le/1390216828562706432 is the …
=> Change the calico manifest download task to fix the CI error on PowerVS

roles/install-k8s/templates/kubeadm.yaml.j2
This will enable multiple entries in the extra_cert variable.
usage:
```json
"extra_cert": "k8s-cluster.ppc64le-cloud.org,651b7744-eu-gb.lb.appdomain.cloud,k8s-cluster-int.ppc64le-cloud.org"
```
=> Enable multiple extra_cert

roles/install-k8s/tasks/main.yml, roles/install-k8s/templates/kubelet.service.j2
- Non Breaking Change to add option parameter. 
- In order to set this parameter optionally, below variable needs to be exported in the prow job shell - 
`export KUBELET_EXTRA_ARGS="--kube-api-qps=100 --kube-api-burst=100 --max-pods 130"`
- No changes required to kubetest2-plugins repo to support this change.
- Next action -> run kubetest2-plugins/hack/build.sh and raise PR for changes.
- Change has been tested and runs fine
=> Adding optional parameter KUBELET_KUBECONFIG_PERF_ARGS  to kubelet config for kube-perf-tests

group_vars/all, roles/install-k8s/tasks/main.yml, roles/install-k8s/templates/kubelet.service.j2
- Fixes issues with https://github.com/ppc64le-cloud/k8s-ansible/pull/17
- extra args for kubelet config can be passed from kubetest command using --extra-args option as key:value pair
- Tested with an e2e execution through kubetest2 tf command and runs fine.
=> Fix for PR #17

roles/install-k8s/tasks/main.yml
This validates 3 conditions and will remove the master node taint only when all of the below conditions are satisfied - 
- workers group does not exist in hosts inventory file
- If workers group is defined but empty
- node_type == "master"
This has been tested and works fine - 
**When both workers and master exist in host file - Taint is not removed** 
```
TASK [install-k8s : remove taint] **************************************************************************************************************************************************************************
skipping: [158.175.162.99]
skipping: [158.175.162.100]
```
**When worker group is defined but is empty (no worker nodes) -Taint is removed** 
Note - Ignore the error as this was tested on a cluster which had no taints and only …
=> Conditional Master Node Taint Removal

roles/install-k8s/tasks/main.yml
This is to avoid an extra domainname getting attached to the hostname in the powervs systems to keep node entries simple.
=> Remove a dummy domain name set during the deployment

install-k8s-perf.yml, roles/perf-cluster-tasks/tasks/main.yml
- Added a new generic perf role - `perf-cluster-tasks` which can be used in the future to add more plays whenever needed for perf runs
- Added 1 play to cordon master node(s)
- Added new install-k8s-perf.yml file as per suggestion with new role inside it.
=> master node cordon code update for perf run

roles/perf-cluster-tasks/tasks/main.yml
- update utility to shell from command as command is unable to correctly process special instructions like "|" which is required.
=> Update to shell from command

roles/install-calico/tasks/main.yml
As per https://github.com/ppc64le-cloud/k8s-ansible/issues/27 I have checked if the download of calico manifest is still needed a limit on the download rate. 
Currently, the download isn't throwing errors in spite of no rate limit.
```
[root@test-calico-dwnload-ratelimit ~]# curl -O https://docs.projectcalico.org/manifests/calico.yaml
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100  197k  100  197k    0     0   242k      0 --:--:-- --:--:-- --:--:--  242k
[root@test-calico-dwnload-ratelimit ~]#
```
The above VM was created today in `prow-testbed-osa21`.
=> Remove the limit on download rate for calico manifest

roles/install-calico/tasks/main.yml
This patch is to use older calico manifest file `v3.20.2` while installing the calico network addon to k8s cluster.
The latest released calico version `v3.21` is failing a conformance test in k8s cluster.
https://github.com/projectcalico/calico/issues/5089
=> Use older calico manifest file

roles/install-k8s/tasks/main.yml
Able to install the `tc` utility when changed to `iproute-tc`.
The playbook ran successfully with changed value.
This is to fix failures of kind https://prow.ppc64le-cloud.org/view/gs/ppc64le-kubernetes/logs/periodic-kubernetes-conformance-test-ppc64le/1460892127763369984
=> Change pre-requisite tc package name to iproute-tc

group_vars/all
Missed adding the # symbol for the line to be commented.
This is causing syntax error :(
https://storage.googleapis.com/ppc64le-kubernetes/logs/periodic-kubernetes-containerd-conformance-test-ppc64le/1473667294881124352/build-log.txt
=> Correct the Syntax Error with group_vars/all

roles/install-k8s/templates/kubeadm.yaml.j2, roles/install-k8s/templates/kubelet.service.j2
For task https://github.ibm.com/powercloud/container-dev/issues/1561
Related PRs:
https://github.com/kubernetes/kubernetes/pull/107013
https://github.com/kubernetes/kubernetes/pull/107295
Related Error:
```
Jan 21 07:57:57 kubeadm-fail kubelet[25421]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kub>
Jan 21 07:57:57 kubeadm-fail kubelet[25421]: Flag --network-plugin has been deprecated, will be removed along with dockershim.
```
Have verified these changes by creating a k8s cluster on PowerVS through this repo.
This is effecting the below jobs:
periodic-kubernetes-storage-perf-test-ppc64le
periodic-kubernetes-containerd-conformance-test-ppc64le
postsubmit-master-golang-kubernetes-conformance-test-ppc64le
ci-search tool link: …
=> Modify kubeadm and kubelet config files used by install-k8s playbook

roles/runtime/tasks/containerd.yaml
Have verified this by provisioning a VM on PowerVS, deploying k8s using this change, and checking if containerd is coming up on its own when the VM is rebooted.
=> Enable containerd service so as to start by default after reboot

roles/install-calico/tasks/main.yml
This is to fix the failures with https://prow.ppc64le-cloud.org/job-history/gs/ppc64le-kubernetes/logs/periodic-kubernetes-containerd-conformance-test-ppc64le
The current playbook uses the `3.20.5` version of calico manifest.
The calico and coredns pods are coming up successfully when the latest stable calico manifest is used from https://docs.projectcalico.org/manifests/calico.yaml
This could be related to the change
(This change happened around the same timestamp as when the tests started failing) https://github.com/projectcalico/calico/commit/0337a6efbfe8e220be55dc3c8483a1790add0724.
```
[root@config1-1650392795-master tmp]# kubectl get pods -n kube-system | grep calico
calico-kube-controllers-7cb7cc646b-7dbt6            0/1     Pending                 0                8h …
```
=> Change the calico manifest to latest version

roles/install-calico/files/calico.yaml, roles/install-calico/tasks/main.yml
Use of manifest from the docs link `https://docs.projectcalico.org/archive/<version>/manifests/calico.yaml` is not a stable one.
It is a dynamic one that keeps streaming updates on a regular and uses the latest patch automatically.
Thus, have made this static based on the one available with 3.22.2 release tarball. 
The one available with release tarball is not a straightforward one that can be used with kubectl apply. It needs the below steps before applying, (as mentioned by the calico maintainer):
- Goto https://github.com/projectcalico/calico/releases/tag/v3.22.2
- Grab the source code archive (either zip or tar.gz)
- unpack the archive somewhere
- change into the calico-3.22.2/calico/ directory
- run make serve - that will start a webserver on your machine and host the docs site
- …
=> Pin calico manifests to v3.22.2

roles/runtime/tasks/containerd.yaml, roles/runtime/tasks/main.yaml
Fixes: #41 
- Moved the prerequisites to the common place for both the runtimes
- Added modules to work properly for boot time
=> Fix the prereq for the container runtime

roles/install-calico/tasks/main.yml, roles/install-k8s/templates/kubeadm.yaml.j2, roles/perf-cluster-tasks/tasks/main.yml
The --bind-address flag for the kube-controller-manager and kube-scheduler is set to 0.0.0.0 from the default 127.0.0.1 to allow the scraping of scheduler-metrics, which are required for `periodic-kubernetes-storage-perf-test-ppc64le` tests.
Additionally, the RBAC for accessing the /metrics API has been configured to be accessed only through GET. A cluster-role and role-binding is defined as one of the tasks during the cluster creation to enable API access during test-execution.
=> Set bind-address for controller-manager and scheduler to 0.0.0.0 and RBAC for /metrics API

group_vars/all, roles/install-calico/tasks/main.yml, roles/runtime/tasks/main.yaml
Changes: 
1. Bump the cri-tools version from v1.24.2 to [v1.26.0](https://github.com/kubernetes-sigs/cri-tools/releases/tag/v1.26.0)
2. Display calico and cri-tools version installed in task during playbook execution.
=> Update cri-tools version installed during K8s infra setup.

group_vars/all, roles/install-calico/tasks/calico-manifest.yaml, roles/install-calico/tasks/calico-operator.yaml, roles/install-calico/tasks/main.yml, roles/install-k8s/templates/kubeadm.yaml.j2
Changes:
1. Update Calico to use the latest release v3.24.5
2. Include option to install Calico using Tigera operator(default).
3. Introduce `installation_type` in `group_vars/all`  to select between operator/manifest based installation.
=> Calico - Version update and operator based installation.

roles/runtime/tasks/main.yaml, roles/runtime/templates/crictl/crictl.yaml.j2
**Requirement:** 
Ability to use crictl to manage the resources hosted on CRI. 
The default endpoints had been deprecated and are required to be set, which otherwise raises the following error upon running commands using crictl:
```
[root@kishen-k8s-master ~]# crictl pods
WARN[0000] runtime connect using default endpoints: [unix:///var/run/dockershim.sock unix:///run/containerd/containerd.sock unix:///run/crio/crio.sock unix:///var/run/cri-dockerd.sock]. 
As the default settings are now deprecated, you should set the endpoint instead.
E0118 15:04:19.571822  177722 remote_runtime.go:277] "ListPodSandbox with filter from runtime service failed" err="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial unix /var/run/dockershim.sock: connect: no …
```
=> Generate crictl.yaml to configure crictl tool

roles/install-k8s/templates/kubeadm.yaml.j2, roles/runtime/files/containerd/dropin.conf, roles/runtime/tasks/containerd.yaml
**Changes in this PR:**
1.  Suppress the warning from kubelet `Flag --container-runtime has been deprecated, will be removed in 1.27 as the only valid value is 'remote'`
2. Set `containerRuntimeEndpoint` through kubeadm.yaml, rather than setting the same through `dropin.conf` as an extra argument during `kubeadm init`.
=> Cleanup: Remove deprecated field `container-runtime` and configure containerRuntimeEndpoint through kubeadm.yaml

roles/install-k8s/tasks/main.yml
This is to fix https://jsw.ibm.com/browse/POWERCLOUD-16
Ref: https://calicousers.slack.com/archives/C0BCA117T/p1677501622349089
=> Add task to disable checksum offload on default network interface

group_vars/all, roles/install-k8s/tasks/main.yml, roles/install-k8s/templates/kubeadm.yaml.j2, roles/runtime/files/crio/crio.service, roles/runtime/files/crio/policy.json, roles/runtime/tasks/crio.yaml, roles/runtime/tasks/main.yaml, roles/runtime/templates/crictl/crictl.yaml.j2
Changes in this PR:
1. Support to use CRI-O as CRI for Kubernetes.
Follow up tasks : 
Additional notes:
- The [binary](https://github.com/kishen-v/crio-ppc64le/blob/main/crio-1.26.tar.gz) for CRI-O needs to be moved from a personal account. WIP for generating builds through GH Actions.
___
 With CRI-O runtime.
```
[root@kishvisw-k8s-m ~]# kubectl get nodes -o wide
NAME             STATUS                     ROLES           AGE   VERSION                           INTERNAL-IP      EXTERNAL-IP   OS-IMAGE          KERNEL-VERSION           CONTAINER-RUNTIME
kishvisw-k8s-m   Ready,SchedulingDisabled   control-plane   52s   v1.27.0-beta.0.8+8b2dae57d4169e   192.168.161.21   <none>        CentOS Stream 8   4.18.0-408.el8.ppc64le   cri-o://1.26.0
kishvisw-k8s-w   Ready                      <none> …
```
=> Add support for CRI-O container runtime. 

examples/containerd-cluster/extra-vars-k8s.json, group_vars/all, hack/k8s-installer.sh, roles/download-k8s/tasks/main.yml
Ref: https://github.com/kubernetes/k8s.io/issues/2396#issue-953342920
Additional notes: Changes had been tested with both alpha and release versions for cluster deployments.
=> Move from storage.googleapis.com to dl.k8s.io for downloads.

group_vars/all, roles/download-k8s/tasks/main.yml
Fixes: https://github.com/ppc64le-cloud/k8s-ansible/issues/57
Verified with downloads from both `dl.k8s.io` and `s3.us-south.cloud-object-storage.appdomain.cloud`
---
For s3.us-south.cloud-object-storage.appdomain.cloud (Partial o/p captured.)
```
TASK [download-k8s : Debug bucket variable] ********************************************************
ok: [192.168.159.220] => {
"src_template": "https://s3.us-south.cloud-object-storage.appdomain.cloud/ppc64le-ci-builds/kubernetes/master/golang/master/7935006af29"
}
ok: [192.168.159.219] => {
"src_template": "https://s3.us-south.cloud-object-storage.appdomain.cloud/ppc64le-ci-builds/kubernetes/master/golang/master/7935006af29"
}
TASK [download-k8s : Extract the k8s bits] *********************************************************
ok: …
```
=> Generate download URL based on s3 bucket.

group_vars/all, roles/runtime/tasks/containerd.yaml, roles/runtime/tasks/crio.yaml, roles/runtime/tasks/main.yaml
The metadata on the docker repository for ppc64le seems to be missing, which is causing an error in the periodic jobs. 
This PR has required changes to retrieve the binary from GitHub. 
Fixes: #59
=> Fetch containerd binary from GitHub.

group_vars/all, k8s-node-remote.yml, roles/disable-swap-selinux/tasks/main.yml, roles/install-bridge-cni/tasks/main.yml, roles/install-bridge-cni/templates/10-bridge-net.conflist.j2, roles/install-etcd/files/etcd.service, roles/install-etcd/tasks/main.yml, roles/k8s-node/tasks/main.yml
This is to add roles for installing `etcd` and `bridge cni` on a node.
Will be used for setting up CI job that runs e2e_node tests of k8s repository.
https://prow.ppc64le-cloud.cis.ibm.net/view/gs/ppc64le-kubernetes/logs/test-periodic-kubernetes-containerd-e2e-node-tests-ppc64le/1717518352693334016
though above job has failed at the stage of using tester, it has successfully passed the phase of using these roles to setup etcd, bridge cni and containerd.
References: https://github.com/etcd-io/etcd/releases
https://github.com/kubernetes/kubernetes/blob/master/hack/local-up-cluster.sh#L1168-L1234
=> Add k8s-node-remote playbook

group_vars/all
Updates the following packages :
* critools :           v1.26.0    -v1.28.0
* runc:      :          v1.1.7       -v1.1.10
* containerd:       v1.7.2      -v1.7.9
* calico CNI :       v3.24.5.  - v3.26.4
---
Validation: 
```
[root@ocp4alll587 ~]# kubectl get nodes -o wide
NAME          STATUS                     ROLES           AGE     VERSION                             INTERNAL-IP    EXTERNAL-IP   OS-IMAGE          KERNEL-VERSION           CONTAINER-RUNTIME
ocp4alll562   Ready                      <none>          5m59s   v1.30.0-alpha.0.15+55f2bc10435160   9.114.99.173   <none>        CentOS Stream 8   4.18.0-365.el8.ppc64le   containerd://1.7.9
ocp4alll587   Ready,SchedulingDisabled   control-plane   6m18s   v1.30.0-alpha.0.15+55f2bc10435160   9.114.99.198   <none>        CentOS Stream …
```
=> Update package versions

roles/disable-swap-selinux/tasks/main.yml, roles/install-k8s/tasks/main.yml
This PR contains the changes to enable the CNI pods to run, which didn't start earlier due to lack of permissions enforced by SELinux. The SELinux policy is now set to "permissive" from "enforced".
```
[root@kishen-k8s-1 ~]# kubectl get pods -A
NAMESPACE     NAME                                       READY   STATUS    RESTARTS     AGE
kube-system   calico-kube-controllers-7c968b5878-rtg9d   1/1     Running   0            89m
kube-system   calico-node-bwcdp                          1/1     Running   0            2m37s
kube-system   calico-node-vth2n                          1/1     Running   0            2m37s
kube-system   coredns-76f75df574-bd6lh                   0/1     Error     1 (2s ago)   89m
kube-system   coredns-76f75df574-zb8zr                   0/1     Error     1 (2s ago) …
```
=> Set SELinux to permissive mode to enable deployment of CNI with cri-o.

group_vars/all, install-k8s-perf.yml, roles/runtime/tasks/crio.yaml
As cri-o builds for ppc64le are made available in the repository, this PR contains changes to make use of the same. The current version to be used is 1.28.1
```
[root@kishen-k8s-1 ~]# kubectl get pods -A
NAMESPACE     NAME                                       READY   STATUS    RESTARTS   AGE
kube-system   calico-kube-controllers-7c968b5878-2kvbd   1/1     Running   0          4m9s
kube-system   calico-node-67xcd                          1/1     Running   0          43s
kube-system   calico-node-r64fc                          1/1     Running   0          43s
kube-system   coredns-76f75df574-d7txc                   1/1     Running   0          4m16s
kube-system   coredns-76f75df574-wl2b6                   1/1     Running   0          4m16s
kube-system   etcd-kishen-k8s-1 …
```
=> Use cri-o from source repository.

k8s-node-remote.yml
`download-k8s` role isn't required here.
The binaries are built when we run the make command here at 
https://github.com/ppc64le-cloud/k8s-ansible/blob/master/roles/k8s-node/tasks/main.yml#L46 thus we don't need a prerequisite for downloading binaries.
=> Remove download-k8s role from k8s-node-remote playbook

group_vars/all, roles/runtime/tasks/containerd.yaml, roles/runtime/tasks/crio.yaml, roles/runtime/tasks/main.yaml
This PR contains changes to update versions for binaries/utilities used by k8s.
|Component|Existing Version|Updated Version|
|-|-|-|
|cri tools|1.28.0|1.29.0|
|runc|1.1.10|1.1.12|
|calico|v3.26.4|v3.27.0|
|crio|1.28.1|1.29.1|
|containerd|1.7.9|1.7.13|
containerd - 1.7.13
```
[root@kishen-k8s-1 ~]# kubectl get nodes -o wide
NAME           STATUS                     ROLES           AGE   VERSION                             INTERNAL-IP     EXTERNAL-IP   OS-IMAGE          KERNEL-VERSION           CONTAINER-RUNTIME
kishen-k8s-1   Ready,SchedulingDisabled   control-plane   67s   v1.30.0-alpha.1.29+6a4e93e776a35d   10.20.181.131   <none>        CentOS Stream 8   4.18.0-408.el8.ppc64le   containerd://1.7.13
kishen-k8s-2   Ready                      <none>          45s …
```
=> Update dependencies to latest availble version.

roles/k8s-node/tasks/main.yml
This change https://github.com/kubernetes/kubernetes/pull/123647 in k8s upstream has started introducing failure to job `periodic-kubernetes-containerd-e2e-node-tests-ppc64le` https://prow.ppc64le-cloud.cis.ibm.net/job-history/gs/ppc64le-kubernetes/logs/periodic-kubernetes-containerd-e2e-node-tests-ppc64le
```
I0303 18:26:52.001612   37232 build.go:59] Building k8s binaries...
F0303 18:26:52.001656   37232 run_local.go:49] Failed to build the dependencies: unable to build cgo targets : failed to locate kubernetes root directory could not find kubernetes source root directory
exit status 255 
```
Export of `KUBE_ROOT` value avoids this failure.
=> Adding KUBE_ROOT value for k8s-node task

roles/k8s-node/tasks/main.yml
The test https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/summary_test.go#L57 fails consistently on ppc64le. Pass `kubelet-flags="--runtime-cgroups=/system.slice/containerd.service` to fix it.
=> Add kubelet flag to resolve summary test failure.

group_vars/all, roles/download-k8s/tasks/main.yml
To improve flexibility of having control over the k8s tarballs that are downloaded.
=> Define tar bundles under group-vars to have control

roles/download-k8s/tasks/main.yml
This task added would import the ctr images from .tar files in /usr/local/bin.
In the below test run, have displayed the verbose of `kubeadm init` and made sure images are not pulled and used from existing ones in runtime.
Test Run: https://storage.googleapis.com/ppc64le-kubernetes/logs/test-periodic-kubernetes-containerd-conformance-test-ppc64le/1849756631768764416/build-log.txt
=> Task to import container images to nodes

roles/install-nfs/tasks/main.yaml
Conditionally remove control-plane taint to avoid errors when taint is absent
- Added a pre-check to verify the existence of the 'node-role.kubernetes.io/control-plane' taint using a shell command.
- Updated the taint removal logic to execute only if the taint is present, preventing unnecessary errors.
=> Add pre-check to conditionally remove control-plane taint

group_vars/all, roles/k8s-ut/tasks/main.yml
This option is required when we wish to run the k8s UT against a specific release branch.
=> Add k8s_branch variable required for k8s_ut role

group_vars/all, install-k8s.yml, roles/disable-swap-selinux/tasks/main.yml, roles/install-flannel/tasks/main.yml, roles/install-k8s/tasks/main.yml, roles/k8s-node/tasks/main.yml, roles/k8s-ut/tasks/main.yml, roles/runtime/tasks/containerd.yaml, roles/runtime/tasks/crio.yaml, roles/runtime/tasks/main.yaml
This adds s390x support. Conditionals were added to handle the Ansible playbook execution which uses ansible_pkg_mgr and ansible_architecture variables. 
Tested the same by executing unit tests, node e2e tests, and conformance tests.
=> Add s390x support

README.md
This is a small change in the document as running from the repo-root seems to break as paths are relative in the shell script.
=> Update instructions to install k8s on PowerVS nodes

group_vars/all
Switching to the default port which is now available in the powervs environment.
=> use 6443 for apiserver

group_vars/all, hack/k8s-installer.sh, roles/install-calico/tasks/calico-manifest.yaml, roles/install-k8s/tasks/main.yml, roles/install-k8s/templates/kubeadm.yaml.j2
Steps that involve setting up of multinode HA cluster.
```
2CP/2Worker setup using a load-balancer.
[root@p10-image-builder hack]# ./k8s-installer.sh -c "10.20.183.177 10.20.183.90" -w "10.20.183.81 10.20.183.18" -l 10.20.183.226 -r -y
10.20.183.177 is reachable
10.20.183.90 is reachable
10.20.183.81 is reachable
10.20.183.18 is reachable
Fetching latest k8s stable release version.
Stable release version to be used for cluster deployment: v1.32.2
Approved to run playbooks after initialization
No playbook has been passed, defaulting to install-k8s.yml
Ansible Playbook   : install-k8s.yml
Control Node IP    : 10.20.183.177 10.20.183.90
Worker Node IP(s)  : 10.20.183.81 10.20.183.18
...
...
PLAY RECAP ******************************************************************************************** …
```
=> Include option to setup a multinode cluster
